name: terraform testing

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
