name: CI Pipeline

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: checkout code verification
        run: |
          ls -l
          pwd
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0  # Specify the Terraform version
      - name: Terraform version check
        run: terraform --version
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deployment job
        run: echo "Deployment job starting.."
