name: CI Pipeline

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: checkout code verification
        run: |
          ls -l
          pwd
